### ISSUE TITLE
Run DMlib upload in Powershell cmdlets on FIPS enabled machine, will get : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

### ISSUE THREAD

**Issue by blueww** [Azure/azure-storage-net-data-movement#186]
### Which service(blob, file) does this issue concern? 
This comes from the PSH issue: https://github.com/Azure/azure-powershell/issues/9908

 
### Which version of the SDK was used?
1.0.0

### On which platform were you using? (.Net Framework version or .Net Core version, and OS version)
Net Standard 2.0 + .NET frameworks 4.7.2 + Winsows 10

### How can the problem be reproduced? It'd be better if the code caused the problem can be shared.
Run Powershell cmdlet Set-AzStorageBlobContent on FIPS enabled machine (use Az.Stoage 1.5.1)

 
### What problem was encountered?
Upload single file get : This implementation is not part of the Windows Platform FIPS validated cryptographic algorithms.

Stack trace:
PS C:\temp> $error[0].Exception.StackTrace
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   at System.Security.Cryptography.IncrementalHash.GetHashAlgorithm(HashAlgorithmName hashAlgorithm)
   at System.Security.Cryptography.IncrementalHash.CreateHash(HashAlgorithmName hashAlgorithm)
   at Microsoft.Azure.Storage.DataMovement.MD5Wrapper..ctor()
   at Microsoft.Azure.Storage.DataMovement.MD5HashStream..ctor(Stream stream, Int64 lastTransferOffset, Boolean md5hashCheck)
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.StreamedReader.<OpenInputStreamAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.Storage.DataMovement.TransferControllers.StreamedReader.<DoWorkInternalAsync>d__16.MoveNext()

### Have you found a mitigation/solution?
No

**Comment by blueww** [comment]
This is already fixed in DMlib 1.1.0

**Comment by atlhon55** [comment]
Hello,
There is the same issue with the command Add-AzVHD on a FIPS enabled machine. I've updated the Az module to its latest version but still have the issue.

DEBUG: AzureQoSEvent: CommandName - Add-AzVhd; IsSuccess - False; Duration - 00:00:02.5217125; Exception -
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. --->
System.InvalidOperationException: This implementation is not part of the Windows Platform FIPS validated cryptographic
algorithms.
   at System.Security.Cryptography.MD5CryptoServiceProvider..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters,
CultureInfo culture)
   at System.Security.Cryptography.CryptoConfig.CreateFromName(String name, Object[] args)
   at System.Security.Cryptography.MD5.Create()
   at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.GetMutexName(Uri destinationBlobUri)
   at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.AcquireSingleInstanceMutex(Uri destinationBlobUri)
   at Microsoft.WindowsAzure.Commands.Sync.Upload.BlobCreatorBase.Create()
   at Microsoft.Azure.Commands.Compute.Models.VhdUploaderModel.Upload(UploadParameters uploadParameters)
   at Microsoft.Azure.Commands.Compute.StorageServices.AddAzureVhdCommand.ExecuteCmdlet()
   at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord();
DEBUG: Finish sending metric.
DEBUG: 09:12:04 - AddAzureVhdCommand end processing.

in workaround, I can now use the command set-azstorageblobcontent as now it works as expected

**Comment by blueww** [comment]
@athlon55 
For Add-AzVHD , please open an issue in https://github.com/Azure/azure-powershell/issues, and the related team will follow up it.
