### ISSUE TITLE
Timeout while DownloadDirectoryAsync is running

### ISSUE THREAD

**Issue by bverhallen** [Azure/azure-storage-net-data-movement#25]
I am trying to get a synchronous blob listing while a large transfer is in progress, using `TransferManager.DownloadDirectoryAsync(...)`

I am seeing a timeout (StorageException) on the following method:

`if (container.Exists(requestOptions: new BlobRequestOptions() { MaximumExecutionTime = _defaultTimeout }) == true)
{ /* get listing */ }`

It doesn't seem to matter how large the timeout is.
If no transfer is running, the above code works just fine.

**Comment by nowenL** [comment]
Your problem looks like a network issues that the data transfer threads used up all network connections/bandwidth. I suggests to have a try on following approach:

1. Increase the .Net http connection limits, it's also mentioned in our DMLib best practice section in the project readme.md.
   ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;

2. If increasing the connection limits does not solve this problem. You can decrease the ParallelOperations settings thus dmlib will have less stress on the network.
   TransferManager.Configurations.ParallelOperations = 10;

**Comment by bverhallen** [comment]
Thank you for your advice!
Unfortunately, neither suggestion, individually or both combined solves the issue.
I tried increasing the connection limit even further and limiting the parallel operations to 2, but to no avail. I am trying this on a very fast fiber network.
If I run AzCopy in a separate process, I can still get listings, albeit somewhat slower than without a transfer.
So I think we can conclude that something is blocking the connection.
What are your thoughts on that?

**Comment by nowenL** [comment]
The variables in Constant is not a part of DMLib interface, most of them are internal magic numbers and can lead to unexpected behaviours if changed. However, MaxCountInTransferWindows should be a "changeable" variable regarding it's usage in the codes.

MaxCountInTransferWindows defines the overall buffer size of each blob being downloaded. It makes the 'downloader' wait for the ‘disk writer’ when the buffer is full. Basically, it has no impact on the download speed as long as the disk is faster than the network. 

So to my best knowledge, this setting seems have nothing to do with your problem. I'm curious how it can be resolved here. Can you share more details about your problem:

  1. Why do you need to list the container again? I'm asking this because you are using DownloadDirectoryAync which will list the blobs for download itself.
  2. Does the timeout issue repro consistently while dmlib is downloading data, what's the error message? 
  3. Does it always happen at Container.Exists method or it can happen somewhere else like the listing codes or the DMLib itself?
  4. What's the size and number of blobs being downloaded here?
  5. Do you have any other setting changed along with the MaxCountInTransferWindow?

**Comment by bverhallen** [comment]
To answer your questions:
1. I'm making a graphical UI around an Azure storage account. While it's downloading, it still needs to be responsive, in this case a user is browsing through containers while downloading.
2. Yes, I am consistently seeing a Microsoft.WindowsAzure.Storage.StorageException:
Message: The operation has timed out.
Stack trace:
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.Exists(Boolean primaryOnly, BlobRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer.Exists(BlobRequestOptions requestOptions, OperationContext operationContext)
3. It happens on basically everything I do on Azure, it now just happened to be an Exists() check in my listing function. If I remove the check, then I see the same behaviour on blobContainer.ListBlobs()
4. I'm downloading 9 blobs, 49 GB in total, but it seems to occur whenever the size is substantial, i.e. download not completed within seconds.
5. Based on your earlier advice, I have set ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
Without it, the timeouts re-occur. But with the MaxCountInTransferWindow set to 128 it happens whether ServicePointManager.DefaultConnectionLimit is set or not.
I played around with the MaxCountInTransferWindow value and what I see is the higher its value, the more likely the timeouts are. In my case, when set to 64, timeouts occur, but not always. Keep in mind this is regardless of the timeout value.
The value of 16 seems to be some kind of sweet spot where I don't see any timeouts.

I hope this helps!

**Comment by nowenL** [comment]
Thanks your very much for the details. 

According to your description, one possibility I can think of is the disk writing speed is slower than the download speed. Thus, the smaller MaxCountInTransferWindow is, the shorter timer it would take for the downloader to stop waiting for the disk. Then the network is spared for the http calls made by your own codes.

Both of dmlib and your codes are using the storage library for C# to send http requests, so I'm not sure why the http requests sent by your code get starving because of the data transfer performed by DMLib while the DMLib didn't timeout.

Could you share the version of storage library for C# you used and how you launch the listing thread. I'd like to have a try and see if I can repro it.

**Comment by bverhallen** [comment]
Thanks for taking the time to figure this out.
Please try the repro code below.
For me, it throws the timeout exception on this line:
var listingResult = GetItems(blobClient, "test");
After changing MaxCountInTransferWindow to 16, it works, although the download takes about twice the time as compared to the 132 setting.
I've tried this on a fast fiber line and on a slow ADSL line with the same results.

using System;
using System.Linq;
using System.Threading.Tasks;
using System.Threading;
using Microsoft.WindowsAzure.Storage;
using Microsoft.WindowsAzure.Storage.Blob;
using Microsoft.WindowsAzure.Storage.DataMovement;
using System.Net;

namespace ConsoleApplication1
{
	class Program
	{
		private TimeSpan _defaultTimeout = new TimeSpan(0, 0, 10);
		private TimeSpan _longTimeout = new TimeSpan(0, 0, 30);

		static void Main(string[] args)
		{
			try
			{
				var p = new Program();
				p.Run();
			}
			catch (Exception exception)
			{
				Console.WriteLine("Error: " + exception.ToString());
			}

		}

		public void Run()
		{
			ServicePointManager.DefaultConnectionLimit = Environment.ProcessorCount * 8;
			ServicePointManager.Expect100Continue = false;

			var accountName = "XXXXXXX";
			var key = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

			var connectionString = $"DefaultEndpointsProtocol=https;AccountName={accountName};AccountKey={key}";
			var storageAccount = CloudStorageAccount.Parse(connectionString);
			var blobClient = storageAccount.CreateCloudBlobClient();

			var dmlibTask = new Task(() =>
			{
				CloudBlobContainer blobContainer = blobClient.GetContainerReference("test");
				var sourceBlob = blobContainer.GetBlockBlobReference("big_file.dat"); // 2 GB file
				
				TransferContext context = new TransferContext();
				context.ProgressHandler = new Progress<TransferProgress>((progress) => { Console.WriteLine("progress: " + progress.BytesTransferred); }); 
				context.OverwriteCallback = (source, destination) => { return true; }; // always overwrite
				
				var downloadTask = TransferManager.DownloadAsync(sourceBlob, @"z:\big.data", new DownloadOptions() { }, context);
				downloadTask.Wait();
			});

			dmlibTask.Start();

			// wait 3 seconds so we're sure that dmlib is running at full speed
			Thread.Sleep(3000);

			// now try to get the listing
			var listingResult = GetItems(blobClient, "test");

			dmlibTask.Wait();
		}


		public IListBlobItem[] GetItems(CloudBlobClient blobClient, string containerName, string virtualDirectoryName = null, bool recursive = false, bool noTimeout = false)
		{
			var container = blobClient.GetContainerReference(containerName);
			if (container.Exists(requestOptions: new BlobRequestOptions() { MaximumExecutionTime = _defaultTimeout }) == true)
			{
				string blobPrefix = null;
				if (String.IsNullOrEmpty(virtualDirectoryName) == false)
				{
					blobPrefix = virtualDirectoryName.TrimStart(new char[] { '/' }) + "/";
				}

				BlobRequestOptions listOptions = null;
				if (noTimeout == false)
				{
					listOptions = new BlobRequestOptions() { MaximumExecutionTime = (recursive == true) ? _longTimeout : _defaultTimeout };
				}
				return container.ListBlobs(blobPrefix, useFlatBlobListing: recursive, blobListingDetails: BlobListingDetails.Metadata, options: listOptions).ToArray();
			}
			else
			{
				return new IListBlobItem[] { };
			}

		}
	}
}

**Comment by bverhallen** [comment]
Any luck yet, reproducing this issue?

Thanks

**Comment by xstof** [comment]
Does this error only occur when using the "data movement library" in process with these other calls to storage?  Or also when you try accessing storage from a completely different executable while the data transfer is happening please?

**Comment by bverhallen** [comment]
It only occurs when using the data movement library.
When I use a different executable during the transfer, it works.
I therefore conclude that the problem must be with the data movement library and not with the network.
It's quite easy to reproduce if you try my sample code above.

**Comment by EmmaZhu** [comment]
@bverhallen 
Which protocol were you using when you got the error? Is it HTTP, or HTTPS? 
Could you set `TransferManager.Configurations.ParallelOperations` to a smaller value to have a try? By default, `TransferManager.Configurations.ParallelOperations` is `Environment.ProcessorCount * 8`.

**Comment by bverhallen** [comment]
@EmmaZhu 
See my comment from March 7 above, I tried setting it to lower values but to no avail.
I am using HTTPS.

**Comment by EmmaZhu** [comment]
@bverhallen 
In your March comments, seems you've tried to set `MaxCountInTransferWindow` instead of `TransferManager.Configurations.ParallelOperations`.  `MaxCountInTransferWindow` is only a value to decide journal chunk size, it doesn't impact parallel level. 
With HTTPS protocol, for proxy handles it different with HTTP protocol, it's very easy to be aborted by proxy when network traffic is high.
Could you try to set `TransferManager.Configurations.ParallelOperations` to a lower value to see whether the issue still exist with lower network traffic?

**Comment by bverhallen** [comment]
@EmmaZhu 
Please check the advice given by @nowenL on March 6, and my test results in my reply on March 7.

Could you try my example code posted on March 11 and see if you can reproduce the problem?

Thanks!

**Comment by EmmaZhu** [comment]
@bverhallen 
We've fixed an issue in the scheduler in DataMovement 0.4.0. Could you try with setting ServicePointManager.DefaultConnectionLimit to a smaller value with the latest DataMovement library to see whether this could you resolve the timeout issue?

**Comment by bverhallen** [comment]
@EmmaZhu 
I've tried version 0.4.0 but unfortunately the issue remains.
Even with ServicePointManager.DefaultConnectionLimit set to 1.
